"""empty message

Revision ID: 463356e9bbb2
Revises: 043c89f8a161
Create Date: 2023-01-31 21:19:51.987744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463356e9bbb2'
down_revision = '043c89f8a161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_pregao', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('item_pregao', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('item_pregao')
        batch_op.drop_column('numero_pregao')

    # ### end Alembic commands ###
