"""empty message

Revision ID: 755811e6b8d5
Revises: cf5eae76a4c3
Create Date: 2023-01-22 12:18:23.953105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755811e6b8d5'
down_revision = 'cf5eae76a4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('super_user',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('super_user',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
