"""empty message

Revision ID: a31de578d760
Revises: d69502d3fb8c
Create Date: 2023-01-23 22:37:53.476036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31de578d760'
down_revision = 'd69502d3fb8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atualizacao_pedido', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('solemp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_solemp', sa.Integer(), nullable=False))
        batch_op.alter_column('pedido_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index('ix_solemp_numero')
        batch_op.create_index(batch_op.f('ix_solemp_numero_solemp'), ['numero_solemp'], unique=False)
        batch_op.drop_column('numero')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solemp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_solemp_numero_solemp'))
        batch_op.create_index('ix_solemp_numero', ['numero'], unique=False)
        batch_op.alter_column('pedido_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('numero_solemp')

    with op.batch_alter_table('atualizacao_pedido', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
