"""empty message

Revision ID: a9d23da34b91
Revises: 755811e6b8d5
Create Date: 2023-01-23 20:33:54.809843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d23da34b91'
down_revision = '755811e6b8d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atualizacao_pedido',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('user_nip', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['user_nip'], ['user.nip'], ),
    sa.PrimaryKeyConstraint('pedido_id', 'user_nip')
    )
    with op.batch_alter_table('atualizacao_pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atualizacao_pedido_timestamp'), ['timestamp'], unique=False)

    op.create_table('item',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('valor_unitario', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('pedido_id')
    )
    op.create_table('solemp',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('pedido_id')
    )
    with op.batch_alter_table('solemp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solemp_numero'), ['numero'], unique=False)

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitacao', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('aprovado', sa.Boolean(), nullable=True))
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.VARCHAR(length=400), nullable=True))
        batch_op.drop_column('aprovado')
        batch_op.drop_column('solicitacao')

    with op.batch_alter_table('solemp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solemp_numero'))

    op.drop_table('solemp')
    op.drop_table('item')
    with op.batch_alter_table('atualizacao_pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atualizacao_pedido_timestamp'))

    op.drop_table('atualizacao_pedido')
    # ### end Alembic commands ###
