"""empty message

Revision ID: b50e398c5c37
Revises: aa703f8adaab
Create Date: 2023-02-20 12:07:54.795323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50e398c5c37'
down_revision = 'aa703f8adaab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao_item', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('observacao', sa.String(length=500), nullable=True))
        batch_op.drop_column('descricao')

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao_pedido', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('justificativa', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('prioridade', sa.String(length=30), nullable=True))
        batch_op.drop_column('solicitacao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitacao', sa.VARCHAR(length=400), nullable=True))
        batch_op.drop_column('prioridade')
        batch_op.drop_column('justificativa')
        batch_op.drop_column('descricao_pedido')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('observacao')
        batch_op.drop_column('descricao_item')

    # ### end Alembic commands ###
