"""Pedidos table

Revision ID: cf5eae76a4c3
Revises: 22145a4b70ce
Create Date: 2023-01-21 22:16:23.467106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf5eae76a4c3'
down_revision = '22145a4b70ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante', sa.String(length=64), nullable=True),
    sa.Column('setor', sa.String(length=30), nullable=True),
    sa.Column('descricao', sa.String(length=400), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_timestamp'))

    op.drop_table('pedido')
    # ### end Alembic commands ###
