"""empty message

Revision ID: d69502d3fb8c
Revises: 65ec788b8468
Create Date: 2023-01-23 22:15:21.726005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd69502d3fb8c'
down_revision = '65ec788b8468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index('ix_item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index('ix_item_id', ['id'], unique=False)

    # ### end Alembic commands ###
